### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'System.Diagnostics.Process, Version=4.0.0.0'

### ISSUE THREAD

**Issue by ibebbs** [Microsoft/ApplicationInsights-dotnet-logging#116]
Hi,

I'm using [Microsoft.ApplicationInsights.EventSourceListener v2.4.0](https://www.nuget.org/packages/Microsoft.ApplicationInsights.EventSourceListener/) to write ETW events to ApplicationInsights from a '.NET Framework 4.6' console application.

I have just started receiving the following error when an event is written (via EventSource.WriteEvent):

```
System.Diagnostics.Tracing.EventSourceException occurred
  HResult=0x80131500
  Message=An error occurred when writing to a listener.
  Source=mscorlib
  StackTrace:
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
   at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, Guid* childActivityID, Object[] args)
   at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, Guid* childActivityID, Int32 eventDataCount, EventData* data)
   at System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data)
   at System.Diagnostics.Tracing.EventSource.WriteEvent(Int32 eventId, String arg1)

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'System.Diagnostics.Process, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

I isolated this to Microsoft.ApplicationInsights.EventSourceListener via Fusion assembly logging where I found this:

```
*** Assembly Binder Log Entry  (25/08/2017 @ 12:34:11) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  [REMOVED]
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Diagnostics.Process, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = [REMOVED]
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = [REMOVED]
Calling assembly : Microsoft.ApplicationInsights.EventSourceListener, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: [REMOVED]
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Diagnostics.Process, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL [REMOVED]
LOG: Attempting download of new URL [REMOVED]
LOG: Attempting download of new URL [REMOVED]
LOG: Attempting download of new URL [REMOVED]
LOG: All probing URLs attempted and failed.

*** Assembly Binder Log Entry  (25/08/2017 @ 12:34:11) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  [REMOVED]
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Diagnostics.Process, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = [REMOVED]
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = [REMOVED]
Calling assembly : Microsoft.ApplicationInsights.EventSourceListener, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: [REMOVED]
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Diagnostics.Process, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL [REMOVED]
LOG: Attempting download of new URL [REMOVED]
LOG: Attempting download of new URL [REMOVED]
LOG: Attempting download of new URL [REMOVED]
LOG: All probing URLs attempted and failed.

*** Assembly Binder Log Entry  (25/08/2017 @ 12:34:11) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  [REMOVED]
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Diagnostics.Process, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = [REMOVED]
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = [REMOVED]
Calling assembly : Microsoft.ApplicationInsights.EventSourceListener, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: [REMOVED]
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Diagnostics.Process, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
ERR: Unrecoverable error occurred during pre-download check (hr = 0x80070002).
```

I am unable to locate the System.Diagnostics.Process assembly anywhere nor am I able to find a nuget package that may be applicable.

This _may_ be related to a recent update to 'Visual Studio 2017 version 15.3' which I upgraded to yesterday (not having seen this issue previously). However, I am unable to confirm this.

Any help or insight would be greatly appreciated.

Regards,
  Ian

**Comment by karolz-ms** [comment]
Seems like it is part of this NuGet package: 

https://www.nuget.org/packages/System.Diagnostics.Process/4.1.0

(yes, the package version is 4.1.0, but the assembly inside the package has assembly version 4.0.0, at least the net46 version).

**Comment by ibebbs** [comment]
Thanks @karolz-ms, I'll try installing that package and seeing if it resolves the error.

Any idea why this is not a dependency of the 'Microsoft.ApplicationInsights.EventSourceListener' package?

**Comment by karolz-ms** [comment]
I should be

https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/develop/src/Adapters/EventSource.Netstandard13/EventSource.Netstandard13.csproj#L26

Not quite sure why it was not restored automatically for you... :-/

**Comment by ibebbs** [comment]
I installed version [4.3.0 of Systems.Diagnostics.Process](https://www.nuget.org/packages/System.Diagnostics.Process/4.3.0) and the error disappeared.

From what I can see, this package isn't in the explicit list of nuget dependencies for [Microsoft.ApplicationInsights](https://www.nuget.org/packages/Microsoft.ApplicationInsights/) or [Microsoft.ApplicationInsights.EventSourceListener](https://www.nuget.org/packages/Microsoft.ApplicationInsights.EventSourceListener/) (although it may be a sub-dependency).

If it should have been restored by some other means I would be very interested to know if this was caused by the upgrade to VS2017v15.3.

Anyway, thank you very much for pointing me at that package. I did search for nuget packages along these lines so not sure how I managed to miss it. Still, back in business now.

**Comment by cijothomas** [comment]
@karolz-ms/ @SergeyKanzhelev  should we be listing the dependencies in the .nuspec as well, not just in .csproj?
I mean in here:
https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/develop/src/NuGet/EventSourceListener/Package.nuspec#L20
(and similar **.nuspecs)

**Comment by karolz-ms** [comment]
@cijothomas Yes, good catch, that is probably what we should be doing

**Comment by cijothomas** [comment]
@karolz-ms ok. Will fix it before next stable release.
